set (IMPORT_NAME "environment")
set (PROJECT_NAME "goma")

file (COPY "${CMAKE_SOURCE_DIR}/src/${PROJECT_NAME}" DESTINATION "/usr/local/bin/")
file (APPEND "/etc/environment" "
#Autogenerated section to import the goma libraries.
LD_LIBRARY_PATH=\"${MPI_TOP}/lib:$LD_LIBRARY_PATH\"
PATH=\"${MPI_TOP}/bin:$PATH\"
PATH=\"${TRILINOS_TOP}/bin:$PATH\"")")

file (WRITE "${CMAKE_SOURCE_DIR}/install_manifest.txt" "/usr/local/bin/${PROJECT_NAME}")
