set (PROJECT_NAME "goma")

file (COPY "${CMAKE_SOURCE_DIR}/src/${PROJECT_NAME}" DESTINATION "/usr/local/bin/")
file (APPEND "$ENV{HOME}/.profile" "
#Autogenerated section to import the goma libraries.
export LD_LIBRARY_PATH=\"${MPI_TOP}/lib:$LD_LIBRARY_PATH\"
export PATH=\"${MPI_TOP}/bin:$PATH\"
export PATH=\"${TRILINOS_TOP}/bin:$PATH\"")

file (APPEND "$ENV{HOME}/.bashrc" "

source ~/.profile")

file (WRITE "${CMAKE_SOURCE_DIR}/install_manifest.txt" "/usr/local/bin/${PROJECT_NAME}")

