#Project name needs to be reset here because it is impossible to pass cmake variables when running make install
set (PROJECT_NAME "goma")

#This copies Goma to /usr/local/bin/goma so it can be executed by running "goma"
file (COPY "${CMAKE_SOURCE_DIR}/src/${PROJECT_NAME}" DESTINATION "/usr/local/bin/")

#This adds a few lines to .profile telling your computer where MPI and Trilinos are.
file (APPEND "$ENV{HOME}/.profile" "
#Autogenerated section to import the goma libraries.
export LD_LIBRARY_PATH=\"${MPI_TOP}/lib:$LD_LIBRARY_PATH\"
export PATH=\"${MPI_TOP}/bin:$PATH\"
export PATH=\"${TRILINOS_TOP}/bin:$PATH\"")

#This makes "make uninstall" work on the newly installed Goma.
file (WRITE "${CMAKE_SOURCE_DIR}/install_manifest.txt" "/usr/local/bin/${PROJECT_NAME}")

