[project]
name = "goma-docs"
version = "0.1.0"
description = "Python configuration for Goma documentation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydata-sphinx-theme>=0.16.1",
    "sphinx>=8.2.3",
]
