FROM rockylinux:8.9

RUN dnf update -y
RUN dnf install -y git patch gcc-toolset-13 m4 make bzip2 tar zlib-devel openssl-devel pkgconfig python3-devel findutils

RUN git clone https://github.com/wortiz/goma -b build-script /opt/goma

RUN . opt/rh/gcc-toolset-13/enable && \
    PYTHONUNBUFFERED=1 /opt/goma/tpls/install-tpls.py --cc=gcc --cxx=g++ --fc=gfortran --build-shared=yes --download-dir=/tmp/downloads -j 32 --extract-dir=/tmp/extract /opt/goma-libs

RUN rm -r /opt/goma

RUN { \
      echo '#!/usr/bin/env bash' \
      && echo ". /opt/rh/gcc-toolset-13/enable" \
      && echo ". /opt/goma-libs/config.sh" \
      && echo 'exec "$@"'; \
    } > /entrypoint.sh \
&& chmod a+x /entrypoint.sh

ARG USER=goma
RUN adduser --disabled-password --gecos '' $USER
RUN adduser $USER sudo; echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# make sure everything is in place
RUN chown -R $USER:$USER /home/$USER
USER $USER
ENV HOME /home/$USER
ENV USER $USER
ENV OMPI_MCA_btl_base_warn_component_unuse "0"
ENV OMPI_ALLOW_RUN_AS_ROOT 1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM 1
WORKDIR $HOME

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/bin/bash" ]


