FROM rockylinux:8.9

RUN dnf update -y
RUN dnf install -y git patch gcc-toolset-13 m4 make bzip2 tar zlib-devel openssl-devel pkgconfig python3-devel findutils

RUN git clone https://github.com/wortiz/goma -b build-script /opt/goma

RUN . opt/rh/gcc-toolset-13/enable && \
    /opt/goma/tpls/install-tpls.py --cc=gcc --cxx=g++ --fc=gfortran --build-shared=yes --download-dir=/tmp/downloads -j 32 --extract-dir=/tmp/extract /opt/goma-libs

RUN { \
      echo '#!/usr/bin/env bash' \
      && echo ". /opt/rh/gcc-toolset-13/enable" \
      && echo ". /opt/goma-libs/config.sh" \
      && echo 'exec "$@"'; \
    } > /entrypoint.sh \
&& chmod a+x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/bin/bash" ]

