FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y git build-essential m4 zlib1g-dev libx11-dev gfortran pkg-config autoconf python3-dev vim tmux nano gdb valgrind libssl-dev curl
RUN apt-get autoremove && apt-get clean

RUN git clone https://github.com/goma/goma /opt/goma

RUN PYTHONUNBUFFERED=1 /opt/goma/tpls/install-tpls.py --cc=gcc --cxx=g++ --fc=gfortran --netlib-blas --build-shared --download-dir=/tmp/downloads -j 32 --extract-dir=/tmp/extract /opt/goma-libs

RUN rm -r /opt/goma
RUN rm -r /tmp/downloads
RUN rm -r /tmp/extract
RUN rm -r /opt/goma-libs/logs

RUN cp /opt/goma-libs/config.sh /etc/profile.d/goma-libs.sh

RUN { \
      echo '#!/usr/bin/env bash' \
      && echo ". /opt/goma-libs/config.sh" \
      && echo 'exec "$@"'; \
    } > /entrypoint.sh \
&& chmod a+x /entrypoint.sh

ENV OMPI_MCA_btl "^vader"
ENV OMPI_MCA_btl_base_warn_component_unuse "0"
ENV OMPI_ALLOW_RUN_AS_ROOT 1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM 1
WORKDIR /opt/workdir

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/bin/bash" ]

