# This adds a few lines to .profile telling your computer where MPI and Trilinos are.

    file (APPEND "$ENV{HOME}/.profile" "
#Autogenerated section to import the goma libraries.
export LD_LIBRARY_PATH=\"${MPI_TOP}/lib:$LD_LIBRARY_PATH\"
export LD_LIBRARY_PATH=\"${TRILINOS_TOP}/lib:$LD_LIBRARY_PATH\"
export PATH=\"${MPI_TOP}/bin:$PATH\"
export PATH=\"${TRILINOS_TOP}/bin:$PATH\"")
