name: Documentation Check Build

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        cache: pip
        with:
          python-version: '3.10'
        run: |
          # install pip=>20.1 to use "pip cache dir"
          pip install --upgrade pip
          pip install --upgrade pipenv
          cd docs
          pipenv install

      - run: |
          cd docs
          pipenv run make github SPHINXOPTS="-W --keep-going -n"
